# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodandoJuntasApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  # Pods for CodandoJuntasApp
  
  # Dependency Injection
  pod 'Swinject', '~> 2.0.0'
  
  #RxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxSwiftUtilities', '~> 2.0.1'
  pod 'Moya/RxSwift'
  pod 'RxSwiftExt'
  pod 'Reusable'
  
  #Clean Code
  pod 'SwiftLint'
  pod 'R.swift'
  
  #Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  
  #UI Utils
  pod 'SnapKit'
  
end
